### ISSUE TITLE
Add "The Secret Garden" by Frances Hodgson Burnett to EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#111]
Info: https://en.wikipedia.org/wiki/The_Secret_Garden

**Comment by ConnectNitish** [comment]
I would like to act on this Issue. Please clarify do we have to design any clip art or so.

**Comment by brittanyrw** [comment]
@ConnectNitish Nope, you do not have to design anything for this Issue! You need to add something like this to the data.js file. And update the information so that it matches the Secret Garden for this Issue. 

```
{
    title: "The Devil Wears Prada",
    author: "Lauren Weisberger",
    emojiImgs: "😈👩🏻‍🦳👠👩🏻👗👛",
    genres: ["drama", "comedy","romance"],
    year: 2003
}
```

Once you add this to the data.js file, JavaScript will automatically turn the emojis into the emoji illustrations that are on the site.
