### ISSUE TITLE
Add "Who Moved My Cheese" by Spencer Johnson to Emoji Pages #127

### ISSUE THREAD

**Issue by TechGirl007** [brittanyrw/emojipages#127]
https://en.wikipedia.org/wiki/Who_Moved_My_Cheese%3F

**Comment by TechGirl007** [comment]
{
    title: "Who Moved My Cheese",
    author: "Spencer Johnson",
    emojiImgs: "🐭🏃🕵️🧀",
    genres: ["fiction", "self-help", "business"],
    year: 1998
     }

**Comment by TechGirl007** [comment]
Learning to understand GitHub from a contribution point of view

**Comment by TechGirl007** [comment]
{
    title: "Who Moved My Cheese",
    author: "Spencer Johnson",
    emojiImgs: "🐭🏃🕵️🧀",
    genres: ["fiction", "self-help", "business"],
    year: 1998
}

**Comment by TechGirl007** [comment]
Hi.  Could we add this to the book list?  Thanks ;)

**Comment by brittanyrw** [comment]
@TechGirl007 Yes, you can add this.
