### ISSUE TITLE
Add Goodreads link for items starting with F to J in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#271]
**If you would like to work on this Issue, comment below and wait for confirmation before starting to code.** 

Add the `itemLink` url for book objects that start with F to J in the data.js file. 

The object currently looks like this:
```
  {
    title: "Diary of A Wimpy Kid",
    author: "Jeff Kinney",
    emojiImgs: "📔🧀🎒🎮",
    genres: ["comedy", "fiction", "young-adult"],
    year: 2007
  }
```

It should now look like this:

```
  {
    title: "Diary of A Wimpy Kid",
    author: "Jeff Kinney",
    emojiImgs: "📔🧀🎒🎮",
    genres: ["comedy", "fiction", "young-adult"],
    year: 2007,
    itemLink: "https://www.goodreads.com/book/show/389627.Diary_of_a_Wimpy_Kid"
  }
```

The `itemLink` should be a link to the book on [Goodreads](https://www.goodreads.com/).

Also for your section of objects (starting with F to J) if they are not already in the correct alphabetical order, please reorder them so that they are in alphabetical order.

**Comment by maxleee** [comment]
hi! if a-e are good I can take the rest of these so they're done.
