### ISSUE TITLE
Add Goodreads link for items starting with N to W in the data.js file

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#273]
**If you would like to work on this Issue, comment below and wait for confirmation before starting to code.** 

Add the `itemLink` url for book objects that start with N to W in the data.js file. 

The object currently looks like this:
```
{
    title: "Nineteen Eighty-Four: A Novel",
    author: "George Orwell",
    emojiImgs: "👀👨🏻👩🏻📕💌🐁",
    genres: ["dystopian", "political-fiction", "science-fiction"],
    year: 1949
  }
```

It should now look like this:

```
{
    title: "Nineteen Eighty-Four: A Novel",
    author: "George Orwell",
    emojiImgs: "👀👨🏻👩🏻📕💌🐁",
    genres: ["dystopian", "political-fiction", "science-fiction"],
    year: 1949,
    itemLink: "https://www.goodreads.com/book/show/40961427-1984"
  }
```

The `itemLink` should be a link to the book on [Goodreads](https://www.goodreads.com/).

Also for your section of objects (starting with N to W) if they are not already in the correct alphabetical order, please reorder them so that they are in alphabetical order.

**Comment by Willumz** [comment]
Hi, I'd love to do this. Figure it's a great way to properly learn how to make a pull request etc.
