### ISSUE TITLE
Add Link to Goodreads shelf to EmojiPages homepage

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#275]
I have created a Goodreads shelf of all of the EmojiPages books and plays and will add books as they are added to the project! Add the link to the shelf inside of the header (tan area).

Goodreads Shelf Link: https://www.goodreads.com/review/list/103445209-emojipages?shelf=emojipages&sort=title

Use the Goodreads font awesome logo: https://fontawesome.com/icons/goodreads?style=brands

Make sure the link opens in a new tab.

The text should read: View Books on Goodreads

Add the link like a button similar to what is on EmojiBops: 
<img width="741" alt="Screen Shot 2019-09-29 at 11 31 12 PM" src="https://user-images.githubusercontent.com/23530405/65847854-40a4c480-e311-11e9-82cf-351eb0b0684f.png">

Feel free to suggest other designs or locations for the links. Let us know if you need more guidance for this issue.

**Comment by tummala-manasa** [comment]
I can work on this. Please assign it to me.

**Comment by MeisterRed** [comment]
Hi, I would like to work on this issue. I'll get started on it very soon

**Comment by brittanyrw** [comment]
Hi @MeisterRed, thanks for working on this!
