### ISSUE TITLE
Add listed item in the data.js

### ISSUE THREAD

**Issue by codewithdev** [brittanyrw/emojipages#290]
**Name of Book or Play **
"Shadow of the Lions"

**Have you confirmed that this has not already been added to the project?**
Check the data.js file, Issues and Pull Requests to make sure you are not adding a duplicate.
 
Yes I've confirmed that this is not presented in the data.js list.

**Comment by brittanyrw** [comment]
Not looking to add additional books to this project at the moment, as outlined in the README.
