### ISSUE TITLE
Add books from The Library 100 (top books of all time) to EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#298]
The OCLC has a list of the top 100 books of all time. Let's add all of these books to EmojiPages. Comment below what you want to add before adding anything please so we can avoid duplicates.

Link to list: https://www.rottentomatoes.com/top/bestofrt/

Below are the books on the list that have not been added to the project yet.

**Instructions**
Please follow these instructions before adding a book:
1. Check the [data.js](https://github.com/brittanyrw/emojipages/blob/master/data.js) file and the [open pull requests](https://github.com/brittanyrw/emojipages/pulls) to make sure the book hasn't already been added.
2. Comment the book(s) you want to add below so we can try to avoid duplicates. You can add multiple but not looking for just one person to add all of the books. 
3. Follow the instructions in the [card overview](https://github.com/brittanyrw/emojipages/blob/master/docs/card_overview.md) to add a books to the project. 
4. If you are adding multiple books from this list, please include them in one pull request

You do not have to wait for confirmation to add something. We will accept the PR from the person that commented first. 

If something is crossed out, someone else is adding that particular movie.

#’s 
20,000 Leagues Under the Sea by Jules Verne

A
A Christmas Carol by Charles Dickens
A Connecticut Yankee in King Arthur's Court by Mark Twain
A Farewell to Arms by Ernest Hemingway
A Journey to the Center of the Earth by Jules Verne
A Portrait of the Artist as a Young Man by James Joyce
A Tale of Two Cities by Charles Dickens
The Adventures of Huckleberry Finn by Mark Twain
The Adventures of Tom Sawyer by Mark Twain
All Quiet on the Western Front by Erich Maria Remarque
Anna Karenina by Leo Tolstoy
Anne of Green Gables by L.M. Montgomery

B
Black Beauty by Anna Sewell
Bleak House by Charles Dickens
Brave New World by Aldous Huxley

C
The Call of the Wild by Jack London
Candide by Voltaire
The Catcher in the Rye by J.D. Salinger
The Complete Sherlock Holmes by Arthur Conan Doyle
The Count of Monte Cristo by Alexandre Dumas
Crime and Punishment by Fyodor Dostoyevsky

D
David Copperfield by Charles Dickens
The Decameron by Giovanni Boccaccio
Doctor Zhivago by Boris Leonidovich Pasternak
Don Quixote by Miguel de Cervantes
Dracula by Bram Stoker

F
Fahrenheit 451 by Ray Bradbury
Far from the Madding Crowd by Thomas Hardy
Fathers and Sons by Ivan Sergeevich Turgenev
The Fellowship of the Ring by J.R.R. Tolkien
For Whom the Bell Tolls by Ernest Hemingway

G
The Grapes of Wrath by John Steinbeck
Great Expectations by Charles Dickens
The Great Gatsby by F. Scott Fitzgerald
Gone with the Wind by Margaret Mitchell
Gulliver's Travels by Jonathan Swift

H
Heidi by Johanna Spyri
The Hobbit, or, There and Back Again by J.R.R. Tolkien
The House of the Seven Gables by Nathaniel Hawthorne
The Hunchback of Notre Dame by Victor Hugo

I
Ivanhoe by Walter Scott

J
The Jungle by Upton Sinclair

K
Kidnapped: The Adventures of David Balfour by Robert Louis Stevenson

L
Lady Chatterley's Lover by D.H. Lawrence
The Last of the Mohicans by James Fenimore Cooper
Little Women by Louisa May Alcott
Lord Jim by Joseph Conrad
Lord of the Flies by William Golding

M
Madame Bovary: Patterns of Provincial Life by Gustave Flaubert
Mansfield Park by Jane Austen
My Ántonia by Willa Cather

O
The Old Man and the Sea by Ernest Hemingway
Oliver Twist  by Charles Dickens
One Hundred Years of Solitude by Gabriel Garcia Márquez

P
Persuasion by Jane Austen
Père Goriot by Honoré de Balzac
Peter Pan by J.M. Barrie
The Picture of Dorian Gray by Oscar Wilde
The Pilgrim's Progress by John Bunyan
Pinocchio by Carlo Collodi
The Prince and the Pauper by Mark Twain
Pride and Prejudice  by Jane Austen

R
The Red Badge of Courage by Stephen Crane
The Red and; the Black by Stendhal
The Return of the King by J.R.R. Tolkien
The Return of the Native by Thomas Hardy

S
The Secret Garden by Frances Hodgson Burnett
Sense and Sensibility by Jane Austen
Sons and Lovers by D.H. Lawrence
The Stranger by Albert Camus
The Swiss Family Robinson by Johann David Wyss

T
Tess of the d'Urbervilles by Thomas Hardy
Treasure Island  by Robert Louis Stevenson
The Three Musketeers by Alexandre Dumas
The Trial by Franz Kafka

U
Ulysses by James Joyce
Uncle Tom's Cabin by Harriet Beecher Stowe

V
The Vicar of Wakefield by Oliver Goldsmith
Vanity Fair by William Makepeace Thackeray

W
White Fang by Jack London
The Wizard of Oz by L. Frank Baum
The Wind in the Willows by Kenneth Grahame
Wuthering Heights by Emily Brontë

**Comment by lajacl** [comment]
I'm adding The Secret Garden and The Wizard of Oz

**Comment by lyndic** [comment]
I'll add "Dracula", "Little Women", and "Pride and Prejudice"

**Comment by rwangca** [comment]
Hi @brittanyrw this is such an awesome project! I'd like to add "Anne of Green Gables by L.M. Montgomery", please let me know if you're still open to contributors. Thank you.

**Comment by brittanyrw** [comment]
@rwangca Yes I am still open to contributions. Please go ahead!
