### ISSUE TITLE
Update emoji cards for mobile

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#31]
In some mobile views, the emojicards no longer look like books. See below for an example. Update the CSS to fix the mobile sizing issues.

<img width="764" alt="emojipages-mobile" src="https://user-images.githubusercontent.com/23530405/65526488-2c9b3600-debf-11e9-93ee-32b1972aed25.png">

**Comment by CodeMeNatalie** [comment]
I can take this one!
