### ISSUE TITLE
Add Goodreads link to items starting with F - J in data.js

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#322]
Add the `itemLink` URL to Goodreads for books that start with F to J in the data.js file.

You can refer to [the link section](https://github.com/brittanyrw/emojipages/blob/master/docs/card_overview.md#link-) in the README.

Updated objects should look like this with a new key named  `itemLink` added to the end of the object. Make sure to separate `itemLink` and `year` with a comma:

```
{
    title: "The Devil Wears Prada",
    author: "Lauren Weisberger",
    emojiImgs: "😈👩🏻‍🦳👠👩🏻👗👛",
    genres: ["drama", "comedy","romance"],
    year: 2003,
    itemLink: "https://www.goodreads.com/book/show/5139.The_Devil_Wears_Prada"
}
```

**Comment by tuzun89** [comment]
Hello,  can I work on this one?

**Comment by brittanyrw** [comment]
@tuzun89 No thanks for this one. You have commented on multiple Issues and I would prefer other people have a chance to contribute. Thanks!
