### ISSUE TITLE
Add a dropdown filter so that users can filter by genre

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#35]
In the top of EmojiPages in the filters section, add a dropdown filter so that users can filter by genre. The options for the filter should include all genres in the data.js file and also in the genres.md genre chart. The filter should be able to automatically pull any new genres someone adds to an emoji card in the future.

Use the colors and styling currently on the website.

You can use the filters on [EmojiScreen](https://emojiscreen.com) as an example of how filters can look, but the design does not have to look exactly like that.

**Comment by markoboy** [comment]
Hello @brittanyrw, is it ok if I take this?

**Comment by brittanyrw** [comment]
@markoboy Yes, but a more abstract, simple version without much detail like the 'record' in EmojiBops and the 'book' in EmojiPages.

<img width="263" alt="Screen Shot 2019-09-27 at 12 08 55 PM" src="https://user-images.githubusercontent.com/23530405/65784272-afbac700-e11f-11e9-9a6b-6e239aeb1636.png">
<img width="207" alt="Screen Shot 2019-09-27 at 12 09 06 PM" src="https://user-images.githubusercontent.com/23530405/65784273-afbac700-e11f-11e9-8a37-e1ef72dc4169.png">

I am working on finishing EmojiGaming and the card is going to be a simplified gameboy. 

So for EmojiScreen, something like this: https://www.iconfinder.com/icons/2166095/old_tv_retro_tv_tv_tv_set_vintage_tv_icon

And instead of the emoji images just being in a white box, they'd be on a 'screen' of some sort. 

I will write more detail for this later tonight!
