### ISSUE TITLE
Add "Charlie and the Chocolate Factory" to by Roald Dahl EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#58]
Info: https://en.wikipedia.org/wiki/Charlie_and_the_Chocolate_Factory

**Comment by alinevillaca** [comment]
Im taking this issue (:

**Comment by alinevillaca** [comment]
@brittanyrw when I try to push, I get this error:
"ERROR: Permission to brittanyrw/emojipages.git denied to alinevillaca.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Can you help me?
