### ISSUE TITLE
Add The Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson to EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#6]
Add The Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson
Book Info: https://en.wikipedia.org/wiki/Strange_Case_of_Dr_Jekyll_and_Mr_Hyde

**Comment by msoegiarto** [comment]
Hi, I'd like to try this one
