### ISSUE TITLE
Add "The Godfather" by Mario Puzo to EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#68]
Info: https://en.wikipedia.org/wiki/The_Godfather_(novel)

**Comment by soumyashaw** [comment]
I was going through the project and just to clear, can you just tell me if I am right. I need to add the emoji card to the data.js after reading about the play or novel?

**Comment by brittanyrw** [comment]
@soumyashaw Yes, you have it correct! You would add something like this to data.js, with the information that matches the Godfather. And it is completely up to you what genres and emojis you use. If you think there's only one genre that fits, it is fine to just add one for example. 🙂

```{
    title: "The Devil Wears Prada",
    author: "Lauren Weisberger",
    emojiImgs: "😈👩🏻‍🦳👠👩🏻👗👛",
    genres: ["drama", "comedy","romance"],
    year: 2003
}
```

When you create your pull request, there will be a checklist that will show up that walks you through all the steps so you can double check if you have everything.  

This is the checklist: https://github.com/brittanyrw/emojipages/blob/master/pull_request_template.md
