### ISSUE TITLE
Add Charlotte’s Web to EmojiPages

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojipages#7]
Add Charlotte’s Web
Book Info: https://en.wikipedia.org/wiki/Charlotte%27s_Web

**Comment by TechGirl007** [comment]
Can I add code for this?

**Comment by TechGirl007** [comment]
{
    title: "Charlotte's Web"
    author: "E.B. White"
    emojiImgs: "🕷️🕸️🖊️🐖👩‍👩‍👧"
    genre: ["Fiction", "Children's", "General"]
    year: 1952
}
